import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/header";
import { Toaster } from "sonner";
import Appprovider from "@/app/app-provider";
import { cookies } from "next/headers";
import SlideSession from "@/components/slide-session";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("sessionToken");
  // console.log(cookieStore)
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <Appprovider initialSessionToken={sessionToken?.value}>
            {" "}
            {children}
            <SlideSession/>
          </Appprovider>
        </ThemeProvider>
      </body>
    </html>
  );
}
